package first;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class MyPanel extends JFrame {

    public JPanel getMainPanel() {
        return mainPanel;
    }

    private JPanel mainPanel;
    private JButton button1Button;
    private JButton button2Button;
    private JLabel myLable;
    private JButton button1;
    private JButton button2;
    private JButton button3;

    public MyPanel() {
        button1Button.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                JOptionPane.showMessageDialog(null, "Wiadomość");
            }
        });
        button2Button.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                myLable.setText(button2Button.getText());
            }
        });
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        mainPanel = new JPanel();
        mainPanel.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        button1Button = new JButton();
        button1Button.setText("Button 1");
        mainPanel.add(button1Button);
        button2Button = new JButton();
        button2Button.setText("Button 2");
        mainPanel.add(button2Button);
        myLable = new JLabel();
        myLable.setText("Label");
        mainPanel.add(myLable);
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new BorderLayout(0, 0));
        mainPanel.add(panel1);
        button1 = new JButton();
        button1.setText("Button");
        panel1.add(button1, BorderLayout.CENTER);
        button2 = new JButton();
        button2.setText("Button");
        panel1.add(button2, BorderLayout.EAST);
        button3 = new JButton();
        button3.setText("Button");
        panel1.add(button3, BorderLayout.SOUTH);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }

}
